### ISSUE TITLE
[Chore] 클라이언트 나의 스터디 페이지 및 자잘한 QA 사항 반영

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#101]
## 🎯 설명
클라이언트 나의 스터디 페이지 및 자잘한 QA 사항을 반영합니다.

## ✅ TODO

- [x] 오늘의 할 일 padWithZero 적용
- [x] wowds 0.1.15 버전으로 변경
- [x] 스터디 커리큘럼 제출하는 시기 이전에 랜더된 버튼은 disabled 처리
- [x] 현재 수강 중인 스터디가 없어요 박스 위치 수정
