### ISSUE TITLE
[Chore] 나의 스터디 페이지 QA 반영

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#115]
## 🎯 설명
나의 스터디 페이지 QA 사항들을 반영합니다.

## ✅ TODO

- [x] 출석체크 모달 하드 코딩된 부분 수정
- [x] 출석체크 시 studyId 대신 studyDetailId로 수정
- [x] 출석체크 완료 이후 버튼 disabled로 처리
- [x] 출석체크 모달 버튼 maxWidth 설정
- [x] 스터디 커리큘럼 휴강주차 표시
- [x] 스터디 공지 UI 깨짐 이슈 해결
- [x] 오늘의 할 일 및 스터디 공지가 없을 때 UI 반영
- [x] 스터디 커리큘럼 태그 UI 다른 부분 수정
- [ ] 스터디 커리큘럼 상세 정보가 없는 경우 처리
