### ISSUE TITLE
[Chore] 과제, 출결 관련 QA사항 반영

### ISSUE THREAD

**Issue by hamo-o** [GDSC-Hongik/wow-class#117]
## ✅ TODO

- [x] [과제 리스트 간격 UI](https://www.notion.so/QA-UI-fa1aa1d8de254498be0967fc6bc72e5b?pvs=4)
- [x] [출결번호 진행중 상태](https://www.notion.so/QA-6594e74b5eed456b88d18ec430792565?pvs=4)
- [x] [주차별 과제 정렬](https://www.notion.so/QA-UI-4126e33009e44fc1b57f92fe08410f88?pvs=4)
- [x] [과제 종료기한 두줄](https://www.notion.so/QA-f91cf810ec3a456ab228e0cc72e97033?pvs=4)
- [x] [과제 생성/수정 타이틀 누락](https://www.notion.so/QA-3e1c1336e05b488991b5a96f16389244?pvs=4)
- [ ] [과제 마감일 유효성검사](https://www.notion.so/QA-validation-6d8e5ce9afb048ddbbd05491d063d070?pvs=4)
