### ISSUE TITLE
[Chore] 나의 스터디 페이지 QA 반영

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#120]
## 🎯 설명
나의 스터디 페이지 QA 사항들 반영합니다.

## ✅ TODO

- [x] 과제 수행하지 않은 경우 오늘의 할 일 나의 과제 바로가기 버튼 활성화
- [x] 커리큘럼 과제 제출하기 리다이렉트 추가
- [x] 커리큘럼 상세 정보 없는 경우 처리
