### ISSUE TITLE
[Chore] 나의 스터디 페이지 QA 반영

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#127]
## 🎯 설명
나의 스터디 페이지 QA 반영했습니다.

## ✅ TODO

- [x] 출석번호 에러 상태 띄우지 못하는 에러 수정
- [x] 출석번호 trim 기능 추가
- [x] 출석번호 textarea 줄바꿈 금지
- [x] 메타데이터 타이틀 수정
- [x] 제출한 과제 확인 버튼 줄바꿈 안 되도록 수정
- [x] 오늘의 할 일 과제 박스 버튼 비활성화 조건 삭제
- [x] 오늘의 할 일 맨 마지막에 도달 시 오른쪽 버튼 안 보이게 수정
- [x] 출석체크 모달에서 api fetch 대신 쿼리 파라미터로 수정
- [x] textfield placeholder ui 변경
- [x] 커리큘럼에서 나의 과제 페이지로 이동 시 외부 링크로 열리지 않게 수정
