### ISSUE TITLE
[Feature] CI/CD 유용한 툴 추가하기

### ISSUE THREAD

**Issue by eugene028** [GDSC-Hongik/wow-class#16]
## 🎯 설명
코드리뷰에서 @hamo-o 님과 @SeieunYoo 님이 제안해 주신 CI/CD 툴을 포함합니다~
## ✅ TODO
- [ ] jest CI/CD
- [ ] lighthouse CI/CD
- [ ] AI가 코드리뷰해주는 툴 사용해보기
