### ISSUE TITLE
[Feature] 수료 회원 처리 및 철회

### ISSUE THREAD

**Issue by hamo-o** [GDSC-Hongik/wow-class#165]
## 🎯 설명
수료 회원 처리 및 철회 모달을 구현합니다.
<img width="915" alt="image" src="https://github.com/user-attachments/assets/9db01aa7-beee-4427-8f56-cd14657dee85">

## ✅ TODO

- [x] 드롭다운에 수료 옵션 추가, 버튼 텍스트 변경
- [x] 우수회원과 수료회원을 구분할 수 있는 타입 추가, 타입에 따른 API 요청 선택
- [x] 수료 처리/철회 API 연결
