### ISSUE TITLE
[Feature] 스터디 개설 페이지 생성 (어드민)

### ISSUE THREAD

**Issue by eugene028** [GDSC-Hongik/wow-class#22]
## 🎯 설명
<img width="663" alt="스크린샷 2024-08-13 오후 6 21 04" src="https://github.com/user-attachments/assets/9e2251e7-0c54-4ffe-a7bb-813e90def985">

<img width="662" alt="스크린샷 2024-08-13 오후 6 21 15" src="https://github.com/user-attachments/assets/c7a24843-f36e-4237-a3e5-c70441b5e321">

스터디 개설 페이지를 생성해요
## ✅ TODO
- [x] 스터디 개설 대시보드
- [x] 멘토/어드민 역할에 따라 보이는 뷰 다르게 하기
- [x] 스터디 개설 api 연결
