### ISSUE TITLE
[Feature] 나의 스터디 페이지 api 연결

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#28]
## 🎯 설명
나의 스터디 페이지 api를 연결합니다.

## ✅ TODO

- [x] 수강 중인 스터디 api 연결
- [x] 스터디 기본 정보 api 연결
- [x] 오늘의 할 일 api 연결
- [x] 스터디 커리큘럼 api 연결
- [x] 스터디 공지 api 연결
- [x] 출석체크 api 연결
