### ISSUE TITLE
[Bug] 스터디 개설하기 버그 수정

### ISSUE THREAD

**Issue by eugene028** [GDSC-Hongik/wow-class#78]
## 🎯 설명
스터디 개설하기 화면에서 마주하는 자잘한 에러들을 해결해요
## ✅ TODO
- [x] 모든 스터디 정보를 입력함에도 불구하고 생성하기 버튼이 validation 처리되지 않는 문제
- [x] queryString 파싱 방식 개선
- [x] 스터디 주차 선택을 먼저 해야 스터디 기간을 선택할 수 있도록 변경
