### ISSUE TITLE
[Bug] 클라이언트 나의 스터디 페이지 QA 반영

### ISSUE THREAD

**Issue by ghdtjgus76** [GDSC-Hongik/wow-class#83]
## 🎯 설명
클라이언트 나의 스터디 페이지 QA 사항 반영합니다.

## ✅ TODO

- [x] 로고 클릭 시 홈으로 가도록 라우팅 추가
- [x] 외부 링크 클릭 시 별도 탭으로
- [x] 멘토 페이지로 전환 버튼 클릭 시 프로덕션/개발 환경에 따라 라우팅되도록 설정
- [x] 소개 링크 null인 경우 예외 처리 추가
- [x] 헤더 반응형 적용
