### ISSUE TITLE
[Bug] 수강 신청 페이지, 마이 페이지 QA 

### ISSUE THREAD

**Issue by SeieunYoo** [GDSC-Hongik/wow-class#85]
## ✅ TODO

- [x] 스터디 타이틀 elipsis
- [x] 수강 신청 중복 
- [x] 테이블 정렬
- [x] 한줄소개 null 일 때 처리
- [x] 반응형 테이블
- [x] 수강 신청 이후 자동으로 모달 닫기
